<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class MakeModuleCommand extends Command
{
    protected $signature = 'module:make
        {category : Module category namespace, for example Platform or Inventory}
        {module : Module name namespace, for example Identity or Catalog}
        {--with-routes : Kept for compatibility; Routes/web.php is generated by default}
        {--with-tests : Generate module test placeholders}
        {--force : Overwrite existing generated files}
        {--dry-run : Show planned files without writing them}';

    protected $description = 'Create a minimal DDD-lite module scaffold.';

    public function handle(): int
    {
        $category = $this->normalizeSegment((string) $this->argument('category'));
        $module = $this->normalizeSegment((string) $this->argument('module'));

        if ($category === null || $module === null) {
            $this->error('Category dan module hanya boleh berisi huruf, angka, spasi, underscore, atau dash.');

            return self::FAILURE;
        }

        $modulePath = app_path("Modules/{$category}/{$module}");
        $files = $this->plannedFiles($category, $module);

        if (File::exists($modulePath) && ! $this->option('force') && ! $this->option('dry-run')) {
            $this->error("Module {$category}/{$module} sudah ada. Gunakan --force jika ingin overwrite file generated.");

            return self::FAILURE;
        }

        if ($this->option('dry-run')) {
            $this->info("DRY RUN module {$category}/{$module}");

            foreach (array_keys($files) as $path) {
                $this->line($this->relativePath($path));
            }

            return self::SUCCESS;
        }

        foreach ($files as $path => $content) {
            File::ensureDirectoryExists(dirname($path));

            if (File::exists($path) && ! $this->option('force')) {
                $this->warn('Skip existing: '.$this->relativePath($path));

                continue;
            }

            File::put($path, $content);
            $this->line('Created: '.$this->relativePath($path));
        }

        $this->info("Module {$category}/{$module} berhasil dibuat.");

        return self::SUCCESS;
    }

    /**
     * @return array<string, string>
     */
    private function plannedFiles(string $category, string $module): array
    {
        $files = [
            app_path("Modules/{$category}/{$module}/ServiceProvider.php") => $this->serviceProviderStub($category, $module),
            app_path("Modules/{$category}/{$module}/Routes/web.php") => $this->webRouteStub(),
            app_path("Modules/{$category}/{$module}/Database/Migrations/.gitkeep") => '',
            app_path("Modules/{$category}/{$module}/Database/Seeders/{$module}DemoSeeder.php") => $this->demoSeederStub($category, $module),
        ];

        if ($this->option('with-tests')) {
            $files[base_path("tests/Feature/Modules/{$category}/{$module}/{$module}ScaffoldTest.php")] = $this->featureTestStub($category, $module);
            $files[base_path("tests/Unit/Modules/{$category}/{$module}/.gitkeep")] = '';
        }

        return $files;
    }

    private function normalizeSegment(string $value): ?string
    {
        $value = trim($value);

        if ($value === '' || ! preg_match('/^[A-Za-z][A-Za-z0-9 _-]*$/', $value)) {
            return null;
        }

        return Str::studly($value);
    }

    private function serviceProviderStub(string $category, string $module): string
    {
        return <<<PHP
<?php

namespace App\\Modules\\{$category}\\{$module};

use Illuminate\\Support\\ServiceProvider as BaseServiceProvider;

class ServiceProvider extends BaseServiceProvider
{
    public function register(): void
    {
        //
    }

    public function boot(): void
    {
        if (is_file(__DIR__.'/Routes/web.php')) {
            \$this->loadRoutesFrom(__DIR__.'/Routes/web.php');
        }

        if (is_dir(__DIR__.'/Database/Migrations')) {
            \$this->loadMigrationsFrom(__DIR__.'/Database/Migrations');
        }
    }
}

PHP;
    }

    private function demoSeederStub(string $category, string $module): string
    {
        return <<<PHP
<?php

namespace App\\Modules\\{$category}\\{$module}\\Database\\Seeders;

use Illuminate\\Database\\Seeder;

class {$module}DemoSeeder extends Seeder
{
    public function run(): void
    {
        //
    }
}

PHP;
    }

    private function webRouteStub(): string
    {
        return <<<'PHP'
<?php

use Illuminate\Support\Facades\Route;

Route::middleware(['web'])->group(function () {
    //
});

PHP;
    }

    private function featureTestStub(string $category, string $module): string
    {
        return <<<PHP
<?php

namespace Tests\\Feature\\Modules\\{$category}\\{$module};

use Tests\\TestCase;

class {$module}ScaffoldTest extends TestCase
{
    public function test_module_scaffold_exists(): void
    {
        \$this->assertFileExists(app_path('Modules/{$category}/{$module}/ServiceProvider.php'));
    }
}

PHP;
    }

    private function relativePath(string $path): string
    {
        $relativePath = str_replace(base_path().DIRECTORY_SEPARATOR, '', $path);

        return str_replace(DIRECTORY_SEPARATOR, '/', $relativePath);
    }
}
